#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define QUICK_TAP_TERM 0

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "7ynGw/aNPvWb"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 14

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

